version: '2'

services:

  drv-load:
    build:
      context: ./module
      dockerfile: Dockerfile.template
      args:
        # Modify to the desired balenaOS version
#        OS_VERSION: 2.108.27
        OS_VERSION: 6.5.9

    privileged: true
    restart: on-failure

  drv-check:
    build:
      context: ./check
      dockerfile: Dockerfile.template
    depends_on:
      - drv-load

  UI:
    build:
      context: ./ui
      dockerfile: Dockerfile.template
    privileged: true  # <-- Easiest, but not always best for production
    environment:
      - UDEV=1
    devices:
      - /dev/input
      - /dev/input:/dev/input
      - /dev/uinput
      - /dev/uinput:/dev/uinput
      - /dev/tty
      - /dev/tty:/dev/tty
      - /dev/fb0
      - /dev/fb0:/dev/fb0
    #volumes:
    #  - /tmp/.X11-unix:/tmp/.X11-unix
    #  - /run/dbus:/run/dbus
    #  - /dev:/dev
